### ISSUE TITLE
驱动安装提示设备识别失败

### ISSUE THREAD

**Issue by ShawnZhou997** [unitreerobotics/kinect_teleoperate#1]
你好，我的驱动安装完成后识别不到设备，左上角选择设备这里提示No Avaliable devices可能是什么原因呢？

不成功后我又用官网github上的驱动安装流程安装另外一个驱动安装并启动成功了，但是k4aviewer仍然用不了

**Comment by ShawnZhou997** [comment]
安装KinectV2的驱动失败

**Comment by silencht** [comment]
你好！
该库是基于 Azure Kinect DK 设备开发的，所以驱动程序可能并不适配 Kinect V2。

**Comment by ShawnZhou997** [comment]
> 你好！ 该库是基于 Azure Kinect DK 设备开发的，所以驱动程序可能并不适配 Kinect V2。

好的，谢谢。
